FROM openjdk:8
COPY /split-data-security-0.0.1-SNAPSHOT.jar /opt/split-data-security-0.0.1/lib/split-data-security-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/split-data-security-0.0.1-SNAPSHOT.jar"]